<?php 

namespace App\Cards\Dtos;

class CardDto {

    public function __construct(
        public ?string  $link = null,
        public ?string  $logo = null,
        public ?string  $test_seal = null,
        public ?string  $test_seal_url = null,
        public ?int     $bank_id = null,
        public ?int     $product_id = null,
        public ?array   $description = null,
        public ?string  $custom_description = null,
        public ?string  $custom_product_name = null,
        public ?string  $bank = null,
        public ?string  $product = null,
        public ?float   $rating = null,
        public ?int     $evaluation_number = null,
        public ?float   $incentive = null,
        public ?float   $fees = null,
        public ?float   $cost = null,
        public ?bool    $bonusprogram = null,
        public ?bool    $insurance = null,
        public ?bool    $benefits = null,
        public ?bool    $services = null,
        public ?array   $special_features = null,
        public ?string  $fees_action = null,
        public ?string  $cost_action = null,
        public ?string  $custom_cost_action = null,
        public ?float   $fees_first_year = null,
        public ?float   $fees_after_first_year = null,
        public ?float   $gc_atmfree_domestic = null,
        public ?float   $gc_atmfree_international = null,
        public ?float   $cc_atmfree_domestic = null,
        public ?float   $cc_atmfree_international = null,
        public ?float   $incentive_amount = null,
        public ?float   $interest_rate = null,
        public ?float   $shall_interest_rate = null,
        public ?int     $cardtype = null,
        public ?string  $cardtype_text = null,
        public ?float   $cc_atmfree_euro = null,
        public ?bool    $kkoffer = null,
        public ?string  $content_crc = null,
    ) {}



    public static function fromXml($product): self {

        return new self(
            description : (array)$product->anmerkungen,
            bank : (string)$product->bank,
            product : (string)$product->produkt,
            rating : (float)$product->bewertung,
            evaluation_number : (bool)$product->bewertung_anzahl,
            incentive : (float)$product->incentive,
            fees : (float)str_replace(',', '.', $product->gebuehren),
            cost : (float)str_replace(',', '.', $product->kosten),
            bonusprogram : (bool)$product->bonusprogram,
            insurance : (bool)$product->insurances,
            benefits : (bool)$product->benefits,
            services : (bool)$product->services,
            special_features : (array)$product->besonderheiten,
            fees_action : (string)$product->gebuehrenmitaktion,
            cost_action : (string)$product->kostenmitaktion,
            fees_first_year : (float)str_replace(',', '.', $product->gebuehrenjahr1),
            fees_after_first_year : (float)str_replace(',', '.', $product->dauerhaft),
            gc_atmfree_domestic : (float)str_replace('.', '', $product->gc_atmfree_domestic),
            gc_atmfree_international : (float)$product->gc_atmfree_international,
            cc_atmfree_domestic : (float)str_replace('.', '', $product->cc_atmfree_domestic),
            cc_atmfree_international : (float)$product->cc_atmfree_international,
            incentive_amount : (float)$product->incentive_amount,
            interest_rate : (float)str_replace(',', '.', $product->habenzins),
            shall_interest_rate : (float)str_replace(',', '.', $product->sollzins),
            cardtype : (int)$product->cardtype,
            cardtype_text : (string)$product->cardtype_text,
            cc_atmfree_euro : (float)$product->cc_atmfree_euro,
            kkoffer : (bool)str_replace(',', '.', $product->kkoffer),
            link : (string)$product->link,
            logo : (string)$product->logo,
            test_seal : (string)$product->testsiegel,
            test_seal_url : (string)$product->testsiegel_url,
            bank_id : (int)$product->bankid,
            product_id : (int)$product->productid,
            custom_cost_action : (string)$product->kostenmitaktion,
            content_crc : (string)$product->content_crc,
        );
    }
}