# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Cards\Infrastructure\External\Factory\CardProviderFactory:
        arguments:
            $financeAdsProvider: '@App\Cards\Infrastructure\External\FinanceAds\FinanceAdsProvider'


    App\Cards\Application\Service\CardImportService:
        arguments:
            $cardProviderFactory: '@App\Cards\Infrastructure\External\Factory\CardProviderFactory'
            $cardRepository: '@App\Cards\Domain\Repository\CardsRepositoryInterface'

    App\Cards\Infrastructure\External\FinanceAds\FinanceAdsCardAdapter:
        tags:
            - { name: finance_ads_adapter }

    App\Cards\Infrastructure\External\FinanceAds\FinanceAdsProvider:
        arguments:
            $client: '@http_client'
            $apiUrl: 'https://tools.financeads.net/'
            $adapter: '@App\Cards\Infrastructure\External\FinanceAds\FinanceAdsCardAdapter'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Shared\Infrastructure\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Cards\Domain\Bus\CommandBusInterface:
        class: App\Cards\Infrastructure\Bus\SymfonyCommandBus

    App\Cards\Domain\Message\MessageHandlerInterface:
        class: App\Cards\Application\Handler\ImportCardsHandler

    App\Cards\Infrastructure\Message\SymfonyMessageHandler:
        arguments:
            $handler: '@App\Cards\Domain\Message\MessageHandlerInterface'

    App\Users\Infrastructure\Security\UserProvider:
        arguments:
            $userRepository: '@App\Users\Domain\Repository\UserRepositoryInterface'
            
    App\Users\Domain\Service\TokenGeneratorInterface:
        class: App\Users\Infrastructure\Service\JWTTokenGenerator
        arguments:
            $secretKey: '%env(JWT_SECRET_KEY)%'
            $tokenTtl: 3600 # 1 hora

    App\Users\Application\Service\AuthenticationService:
        arguments:
            $userRepository: '@App\Users\Domain\Repository\UserRepositoryInterface'
            $tokenGenerator: '@App\Users\Domain\Service\TokenGeneratorInterface'
    App\Users\Infrastructure\Security\JWTAuthenticator:
        arguments:
            $tokenGenerator: '@App\Users\Domain\Service\TokenGeneratorInterface'

    App\Shared\Infrastructure\Service\CurrentClientProvider:
        arguments:
            $tokenStorage: '@security.token_storage'

    App\Clients\Domain\Contracts\Client:
        shared: true
        public: true

    App\Clients\Application\Service\TenantManager:
        arguments:
            $container: '@service_container'
            $clientRepository: '@App\Clients\Domain\Repository\ClientRepositoryInterface'

    App\Clients\Infrastructure\EventListener\TenantIdentificationSubscriber:
        tags:
            - { name: kernel.event_subscriber, priority: -10 }
        arguments:
            $tokenStorage: '@security.token_storage'
            $currentClientProvider: '@App\Shared\Infrastructure\Service\CurrentClientProvider'
            $tenantManager: '@App\Clients\Application\Service\TenantManager'

    # Configuración del repositorio con caché
    App\Clients\Domain\Repository\ClientRepositoryInterface:
        class: App\Clients\Infrastructure\Persistence\Doctrine\Repository\DoctrineClientRepository

    # Decorador de caché para el repositorio de clientes
